Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Load T-stat map (3dttest++ and 3dMEMA results)
img_ttest = image.load_img("./afni_pro_glm/group_results/Flanker-Inc-Con_ttest_Tstat.nii.gz")
img_mema = image.load_img("./afni_pro_glm/group_results/Flanker_Inc-Con_MEMA_Tstat.nii.gz")


threshold = 3.3 

# Apply uncorrected voxel threshold (T > 3.3 â‰ˆ p < 0.001)
# and minimum cluster size of 40 voxels
thresholded_img_ttest = image.threshold_img(
    img_ttest,
    threshold=threshold,
    cluster_threshold=40,
    two_sided=True,  
    copy_header=True
    
)

thresholded_img_mema = image.threshold_img(
    img_mema,
    threshold=threshold,
    cluster_threshold=40,
    two_sided=True,
    copy_header=True
    
)

# Plot result
plotting.plot_stat_map(
    thresholded_img_ttest,
    title="3dttest++ (p<0.001, kâ‰¥40 vox)",
    threshold=threshold,
    colorbar=True
)

plotting.plot_stat_map(
    thresholded_img_mema,
    title="3dMEMA (p<0.001, kâ‰¥40 vox)",
    threshold=threshold,
    colorbar=True
)
plotting.show()

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[18], line 2[0m
[1;32m      1[0m [38;5;66;03m# Load T-stat map (3dttest++ and 3dMEMA results)[39;00m
[0;32m----> 2[0m img_ttest [38;5;241m=[39m [43mimage[49m[38;5;241;43m.[39;49m[43mload_img[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43m./afni_pro_glm/group_results/Flanker-Inc-Con_ttest_Tstat.nii.gz[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      3[0m img_mema [38;5;241m=[39m image[38;5;241m.[39mload_img([38;5;124m"[39m[38;5;124m./afni_pro_glm/group_results/Flanker_Inc-Con_MEMA_Tstat.nii.gz[39m[38;5;124m"[39m)
[1;32m      6[0m threshold [38;5;241m=[39m [38;5;241m3.3[39m 

File [0;32m~/.local/lib/python3.10/site-packages/nilearn/image/image.py:1693[0m, in [0;36mload_img[0;34m(img, wildcards, dtype)[0m
[1;32m   1658[0m [38;5;129m@fill_doc[39m
[1;32m   1659[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mload_img[39m(img, wildcards[38;5;241m=[39m[38;5;28;01mTrue[39;00m, dtype[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[1;32m   1660[0m [38;5;250m    [39m[38;5;124;03m"""Load a Niimg-like object from filenames or list of filenames.[39;00m
[1;32m   1661[0m 
[1;32m   1662[0m [38;5;124;03m    .. versionadded:: 0.2.5[39;00m
[0;32m   (...)[0m
[1;32m   1691[0m 
[1;32m   1692[0m [38;5;124;03m    """[39;00m
[0;32m-> 1693[0m     [38;5;28;01mreturn[39;00m [43mcheck_niimg[49m[43m([49m[43mimg[49m[43m,[49m[43m [49m[43mwildcards[49m[38;5;241;43m=[39;49m[43mwildcards[49m[43m,[49m[43m [49m[43mdtype[49m[38;5;241;43m=[39;49m[43mdtype[49m[43m)[49m

File [0;32m~/.local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py:338[0m, in [0;36mcheck_niimg[0;34m(niimg, ensure_ndim, atleast_4d, dtype, return_iterator, wildcards)[0m
[1;32m    336[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(message)
[1;32m    337[0m     [38;5;28;01melse[39;00m:
[0;32m--> 338[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mFile not found: [39m[38;5;124m'[39m[38;5;132;01m{[39;00mniimg[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m"[39m)
[1;32m    339[0m [38;5;28;01melif[39;00m [38;5;129;01mnot[39;00m Path(niimg)[38;5;241m.[39mexists():
[1;32m    340[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mFile not found: [39m[38;5;124m'[39m[38;5;132;01m{[39;00mniimg[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m"[39m)

[0;31mValueError[0m: File not found: './afni_pro_glm/group_results/Flanker-Inc-Con_ttest_Tstat.nii.gz'

